"use client";

import {
  Link,
  Globe,
  Palette,
  Picture,
  Camera,
  Video,
  MusicNote,
  Folder,
  FileText,
  Book,
  BookOpen,
  Calendar,
  Clock,
  ChartLine,
  ChartColumn,
  ChartPie,
  Database,
  Envelope,
  Comments,
  Megaphone,
  Bell,
  Persons,
  PersonWorker,
  GraduationCap,
  Briefcase,
  CreditCard,
  Ticket,
  Tag,
  Target,
  Rocket,
  Bulb,
  Sparkles,
  Star,
  Heart,
  MapPin,
  Flag,
  Puzzle,
  Cube,
  Display,
  Code,
  Cloud,
  Shield,
  Key,
  Wrench,
  Gear,
} from "@gravity-ui/icons";
import { defaultToolIcon, isToolIcon, type ToolIconName, type ToolKind } from "@/lib/domain/tools-shared";

const ICONS: Record<ToolIconName, typeof Link> = {
  Link,
  Globe,
  Palette,
  Picture,
  Camera,
  Video,
  MusicNote,
  Folder,
  FileText,
  Book,
  BookOpen,
  Calendar,
  Clock,
  ChartLine,
  ChartColumn,
  ChartPie,
  Database,
  Envelope,
  Comments,
  Megaphone,
  Bell,
  Persons,
  PersonWorker,
  GraduationCap,
  Briefcase,
  CreditCard,
  Ticket,
  Tag,
  Target,
  Rocket,
  Bulb,
  Sparkles,
  Star,
  Heart,
  MapPin,
  Flag,
  Puzzle,
  Cube,
  Display,
  Code,
  Cloud,
  Shield,
  Key,
  Wrench,
  Gear,
};

/** Ícono de una herramienta; si el guardado no es válido (p. ej. un emoji antiguo), el del tipo. */
export function ToolIcon({ name, kind, size = 20 }: { name: string; kind: ToolKind; size?: number }) {
  const Icon = ICONS[isToolIcon(name) ? name : defaultToolIcon(kind)];
  return <Icon width={size} height={size} aria-hidden />;
}

/** Ícono por nombre (para el selector). */
export function ToolIconByName({ name, size = 20 }: { name: ToolIconName; size?: number }) {
  const Icon = ICONS[name];
  return <Icon width={size} height={size} aria-hidden />;
}
